automotor:
    path:     /
    defaults: { _controller: "GlavBundle:Automotor:index" }

automotor_show:
    path:     /{id}/show
    defaults: { _controller: "GlavBundle:Automotor:show" }

automotor_new:
    path:     /new
    defaults: { _controller: "GlavBundle:Automotor:new" }

automotor_create:
    path:     /create
    defaults: { _controller: "GlavBundle:Automotor:create" }
    methods:  POST

automotor_edit:
    path:     /{id}/edit
    defaults: { _controller: "GlavBundle:Automotor:edit" }

automotor_update:
    path:     /{id}/update
    defaults: { _controller: "GlavBundle:Automotor:update" }
    methods:  [POST, PUT]

automotor_delete:
    path:     /{id}/delete
    defaults: { _controller: "GlavBundle:Automotor:delete" }
    methods:  [POST, DELETE]
