cargo:
    path:     /
    defaults: { _controller: "GlavBundle:Cargo:index" }

cargo_show:
    path:     /{id}/show
    defaults: { _controller: "GlavBundle:Cargo:show" }

cargo_new:
    path:     /new
    defaults: { _controller: "GlavBundle:Cargo:new" }

cargo_create:
    path:     /create
    defaults: { _controller: "GlavBundle:Cargo:create" }
    requirements: { _method: post }

cargo_edit:
    path:     /{id}/edit
    defaults: { _controller: "GlavBundle:Cargo:edit" }

cargo_update:
    path:     /{id}/update
    defaults: { _controller: "GlavBundle:Cargo:update" }
    requirements: { _method: post|put }

cargo_delete:
    path:     /{id}/delete
    defaults: { _controller: "GlavBundle:Cargo:delete" }
    requirements: { _method: post|delete }
