factura:
    path:     /
    defaults: { _controller: "GlavBundle:Factura:index" }

factura_show:
    path:     /{id}/show
    defaults: { _controller: "GlavBundle:Factura:show" }

factura_new:
    path:     /new
    defaults: { _controller: "GlavBundle:Factura:new" }

factura_create:
    path:     /create
    defaults: { _controller: "GlavBundle:Factura:create" }
    methods:  POST

factura_edit:
    path:     /{id}/edit
    defaults: { _controller: "GlavBundle:Factura:edit" }

factura_update:
    path:     /{id}/update
    defaults: { _controller: "GlavBundle:Factura:update" }
    methods:  [POST, PUT]

factura_delete:
    path:     /{id}/delete
    defaults: { _controller: "GlavBundle:Factura:delete" }
    methods:  [POST, DELETE]
    
factura_valor:
    path:     /valor
    defaults: { _controller: "GlavBundle:Factura:valorServicio" }
    #methods:  [POST, DELETE] 
    
factura_guardar:
    path:     /guardar
    defaults: { _controller: "GlavBundle:Factura:guardarFactura" }
    #methods:  [POST, DELETE]

factura_buscar_cliente:
    path:     /buscar
    defaults: { _controller: "GlavBundle:Factura:buscarCliente" }
    #methods:  [POST, DELETE]
    
factura_imprimir:
    path:     /imprimir/{id}
    defaults: { _controller: "GlavBundle:Factura:imprimir" }
    #methods:  [POST, DELETE]