informe:
    path:     /
    defaults: { _controller: "GlavBundle:Informe:empleado" }
    
informe_empleado:
    path:     /empleado
    defaults: { _controller: "GlavBundle:Informe:informeEmpleado" }
    
semanal_empleado:
    path:     /semanal
    defaults: { _controller: "GlavBundle:Informe:informeSemanal" }
    
pagar:
    path:     /pagar
    defaults: { _controller: "GlavBundle:Informe:pagar" }

excel:
    path:     /excel
    defaults: { _controller: "GlavBundle:Informe:excel" }