glav:
    resource: "@GlavBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#FosUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"