glav:
    resource: "@GlavBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#FosUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    #schemes:  [https] #Utilizar Https pero me esta borrando el puerto 

glav_homepage:
    pattern:  /
    defaults: { _controller:GlavBundle:Default:home }