# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
            access_denied_url: /login
            #Enviar a una pagina por defecto al hacer el logueo'Enviar
            #login_path: /login
            #default_target_path: /my/desired/path
            #always_use_default_target_path: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/tipoautomotor/, role: ROLE_SUPER_ADMIN }
        - { path: ^/informe/semanal, role: ROLE_SUPER_ADMIN }
        - { path: ^/tiporubro/, role: ROLE_SUPER_ADMIN }
        - { path: ^/prestamo/, role: ROLE_SUPER_ADMIN }

        #- { path: ^/cliente/, role: ROLE_USER }

