glav_prestamo:
    resource: "@GlavBundle/Resources/config/routing/prestamo.yml"
    prefix:   /prestamo

glav_facturadetalle:
    resource: "@GlavBundle/Resources/config/routing/facturadetalle.yml"
    prefix:   /facturadetalle

glav_factura:
    resource: "@GlavBundle/Resources/config/routing/factura.yml"
    prefix:   /factura

glav_servicio:
    resource: "@GlavBundle/Resources/config/routing/servicio.yml"
    prefix:   /servicio

glav_automotor:
    resource: "@GlavBundle/Resources/config/routing/automotor.yml"
    prefix:   /automotor

glav_rubro:
    resource: "@GlavBundle/Resources/config/routing/rubro.yml"
    prefix:   /rubro

glav_tiporubro:
    resource: "@GlavBundle/Resources/config/routing/tiporubro.yml"
    prefix:   /tiporubro

glav_tipoautomotor:
    resource: "@GlavBundle/Resources/config/routing/tipoautomotor.yml"
    prefix:   /tipoautomotor

glav_cliente:
    resource: "@GlavBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

glav_cargo:
    resource: "@GlavBundle/Resources/config/routing/cargo.yml"
    prefix:   /cargo

glav_empleado:
    resource: "@GlavBundle/Resources/config/routing/empleado.yml"
    prefix:   /empleado
    
glav_informe:
    resource: "@GlavBundle/Resources/config/routing/informe.yml"
    prefix:   /informe

glav_homepage:
    path:     /hello/{name}
    defaults: { _controller: GlavBundle:Default:index }
