<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AutomotorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutomotorRepository extends EntityRepository
{
    public function findAutomotor()
    {
        $qb = $this->createQueryBuilder('a')->where('(a.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
