<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends EntityRepository
{
    public function findCargo()
    {
        $qb = $this->createQueryBuilder('ca')->where('(ca.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
