<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function findCliente()
    {
        $qb = $this->createQueryBuilder('c')->where('(c.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
