<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends EntityRepository
{
    public function findEmpleado()
    {
        $qb = $this->createQueryBuilder('e')->where('(e.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
