<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoRepository extends EntityRepository
{
        public function findPrestamo()
    {
        $qb = $this->createQueryBuilder('p')->where('(p.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
