<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroRepository extends EntityRepository
{
    public function findRubro()
    {
        $qb = $this->createQueryBuilder('r')->where('(r.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
