<?php

namespace GlavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoAutomotorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAutomotorRepository extends EntityRepository
{
    public function findTipoAutomotor()
    {
        $qb = $this->createQueryBuilder('ta')->where('(ta.estado = 1)');
        $query = $qb->getQuery();
        return $query->execute();
    }
}
